apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: guchub
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: guchub
    spec:
      containers:
        - name: guchub
          image: reviewappregistery.azurecr.io/guchub
          ports:
            - containerPort: 3000
