apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: guchub-ingress-__app-id__
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  tls:
  - hosts:
    - guchub-__app-id__.ahmedlhanafy.com
    secretName: tls-secret-__app-id__
  rules:
  - host: guchub-__app-id__.ahmedlhanafy.com
    http:
      paths:
      - backend:
          serviceName: guchub-__app-id__
          servicePort: 80
        path: /(.*)
